### ISSUE TITLE
有上岸的老哥吗,程序员交流群期待来点公务员老哥聊聊(李赣粉丝优先!)

### ISSUE THREAD

**Issue by mayben0t** [coder2gwy/coder2gwy#114]

**Comment by Liangsancun** [comment]
是qq群吗？搜不到这个群呀

**Comment by mayben0t** [comment]
你加我QQ我拉你吧 594180536------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月7日(星期一) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coder2gwy/coder2gwy] 有上岸的老哥吗,程序员交流群期待来点公务员老哥聊聊(李赣粉丝优先!) (#114)

**Comment by mayben0t** [comment]
或者你重新搜索下 刚刚改了下设置哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coder2gwy/coder2gwy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coder2gwy/coder2gwy] 有上岸的老哥吗,程序员交流群期待来点公务员老哥聊聊(李赣粉丝优先!) (#114)





 
是qq群吗？搜不到这个群呀

**Comment by mayben0t** [comment]
人目前有点够了,谢谢^^
