### ISSUE TITLE
是否辞职全职备考3个月

### ISSUE THREAD

**Issue by DrakenZeng** [coder2gwy/coder2gwy#124]
情况是这样：
目前，2020届，毕业一年，在目前公司做了一年。年底也准备跳槽，决策是做到明年拿到年终奖跳槽顺带在职备考。但更想年底辞职，全职备考三个月，考完再找下一份工作。

**Comment by huangsiyuan2015** [comment]
> 情况是这样： 目前，2020届，毕业一年，在目前公司做了一年。年底也准备跳槽，决策是做到明年拿到年终奖跳槽顺带在职备考。但更想年底辞职，全职备考三个月，考完再找下一份工作。

几月份考试啊？一年可以考几次？

**Comment by DrakenZeng** [comment]
参加明年广东省考  大概会在2022的三、四月份期间有事业单位也可以参加考试   地点是广州

**Comment by miss-mumu** [comment]
个人愚见：不太建议你没拿到年终奖就辞职备考。首先，辞职备考3个月，最好的结果是保证你能进面，后续的面试、体检、政审、考察都需要你话时间去准备，去投入。按照今年的惯例，至少会拖到8月份左右。

如果你没拿年终奖就备考，加上你工作时间不长，后续的经济压力反而会影响你的备考心态。

如果你还有公考、体制其他问题，推荐看看我们为coder2gwy的补充项目，[developer2gwy](https://github.com/miss-mumu/developer2gwy)

**Comment by skyabcher** [comment]
建议在职考，压力不会那么大

**Comment by DrakenZeng** [comment]
考试提前了   0.0
