### ISSUE TITLE
感谢coder2gwy项目，向大家自荐我们的项目developer2gwy

### ISSUE THREAD

**Issue by miss-mumu** [coder2gwy/coder2gwy#127]
首先感谢 coder2gwy 这个项目！

我们是一群前码畜，自己瞎摸索，跌跌撞撞上岸。上岸后身边也有很多同事想要进入体制内，所以一直向他们推荐coder2gwy 项目。

同时也感觉，coder2gwy 这几位出自大厂的同学和我们这些外包公司，半路出家的“码畜”在工作、备考、上岸的经历以及心态上还是有点差别的。期间的心酸苦泪，现在和朋友们聊起来还唏嘘不已，当然也庆幸万分。

所以，我们想要根据自己亲身经历（tag：学渣、智商一般、半路出家、外包公司、被社会毒打、跌跌撞撞上岸），分享一份适用于每个普通人的“从入门到上岸”手把手操作实践教程以及整个上岸过程中的心得体会、事后总结，帮助大家避开上岸路上的坑。

并且，分享我们自己和我们身边体制朋友的工作、生活、人际关系、人生思考等等。希望大家能从另一个方面了解体制内这份工作的酸甜苦辣。从而更好的规划、制定自己的职业和人生的走向。

[项目地址](https://github.com/miss-mumu/developer2gwy)

再次感谢coder2gwy项目，你们是我们的领路人！

**Comment by anprettyboy** [comment]
提升一下工作饱和度，减少午休、上厕所等不必要的时间浪费

**Comment by huangsiyuan2015** [comment]
> 首先感谢 coder2gwy 这个项目！
> 
> 我们是一群前码畜，自己瞎摸索，跌跌撞撞上岸。上岸后身边也有很多同事想要进入体制内，所以一直向他们推荐coder2gwy 项目。
> 
> 同时也感觉，coder2gwy 这几位出自大厂的同学和我们这些外包公司，半路出家的“码畜”在工作、备考、上岸的经历以及心态上还是有点差别的。期间的心酸苦泪，现在和朋友们聊起来还唏嘘不已，当然也庆幸万分。
> 
> 所以，我们想要根据自己亲身经历（tag：学渣、智商一般、半路出家、外包公司、被社会毒打、跌跌撞撞上岸），分享一份适用于每个普通人的“从入门到上岸”手把手操作实践教程以及整个上岸过程中的心得体会、事后总结，帮助大家避开上岸路上的坑。
> 
> 并且，分享我们自己和我们身边体制朋友的工作、生活、人际关系、人生思考等等。希望大家能从另一个方面了解体制内这份工作的酸甜苦辣。从而更好的规划、制定自己的职业和人生的走向。
> 
> [项目地址](https://github.com/miss-mumu/developer2gwy)
> 
> 再次感谢coder2gwy项目，你们是我们的领路人！

好棒！start 一个！
