### ISSUE TITLE
希望介绍一些公务员的日常工作

### ISSUE THREAD

**Issue by luhuadong** [coder2gwy/coder2gwy#150]

**Comment by chenyurou** [comment]
同问

**Comment by CityOx** [comment]
比如周期性业务工作：参加会议（上级主办的调度会、推进会，本级主办的讨论会等），请示、向下级分办工作、微信电话等方式督办、统计、分析、汇报。
大城市里，党委机关工作量会很多，基层单位如街道办也是，其他大部分政府部门工作量一般。一般来说不需要加班，真需要加班也没有强迫性，你不违法犯罪，就没有开除一说，躺平最多会成为一个领导眼中的不干活的懒蛋，至于会被怎么治，得看领导的手段。

**Comment by y11en** [comment]
> 

懒蛋就不错了，和干坏事相比
