### ISSUE TITLE
体制内特点 供参考

### ISSUE THREAD

**Issue by chengyi** [coder2gwy/coder2gwy#18]
体制内，有没有关系很重要， 有关系：活不用干，钱拿的多；没关系：活干的多，没钱，领导还骂。
里面各种勾心斗角，无节操无下限。 如果你能做到死猪不怕开水烫，那么体制内可以去。看个人的需求吧~
性价比还是蛮高的~，国家发的都给发，比较少的加班，收入稳定，工作看岗位，有可能年复一年的重复没有意义的工作。
总之，如人饮水， 冷暖自知。

补充下，体制内有的单位 内斗可以到什么地步 天天上演宫斗剧， 排除异己的方法有：
1、打小报告
2、造谣
3、污蔑，比如传你有不正当男女关系
4、挖坑，比如引诱你说出一些话

体制内生存特别要做到 谨言慎行四个字。见到领导即使你不想笑，也要堆出笑脸，这是体制内的礼节，和体制外还是有些差别，
需要我们有颗强大的内心。

我就不说我怎么知道的这么详细了。

**Comment by DavidWhom** [comment]
突然想起以前一个同事，大学毕业后直接考进的事业单位，后面自学编程转行做程序员。

**Comment by chengyi** [comment]
> 
> 
> 突然想起以前一个同事，大学毕业后直接考进的事业单位，后面自学编程转行做程序员。

我身边也听说同样的例子

**Comment by m8282823** [comment]
公务员和事业单位还是差蛮远的，特别如果是不太好的事业单位的话

**Comment by tonesCottage** [comment]
围城  把996的程序员，缺点说出来  也是一箩筐 没啥

**Comment by yingqulee** [comment]
友情提醒，不是所有人都适合程序员

**Comment by chengyi** [comment]
> 
> 
> 公务员和事业单位还是差蛮远的，特别如果是不太好的事业单位的话

今年疫情 影响财政收入， 你懂的

**Comment by chengyi** [comment]
> 
> 
> 围城 把996的程序员，缺点说出来 也是一箩筐 没啥
正解， 不存在没有缺点的工作， 找适合自己的
