### ISSUE TITLE
【上岸教师贴】如何上岸发达地区在编教师全攻略

### ISSUE THREAD

**Issue by whubaichuan** [coder2gwy/coder2gwy#38]
大家好，我是计算机应届硕士，大家可以看到我的github仓库，也是搞过开源搞过论文的好学生。

后来经过多家公司的实习经历和个人感悟，最终还是选择进入体制内。

针对此，我写过这些[文章](https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NTEwNTI0Nw==&action=getalbum&album_id=1610763466921787393#wechat_redirect)：

[我眼中的深圳30万起薪教师岗](https://mp.weixin.qq.com/s?__biz=MzA4NTEwNTI0Nw==&mid=2247484308&idx=1&sn=95f92271848a540e854eced0f092ce34&chksm=9fdc4ca4a8abc5b2d42ab0ca3c7f30b429ac16fb0220389e691cf36e67f15e03c825e8985c4e&scene=178&cur_album_id=1610763466921787393#rd)
[产品，金融，算法？](https://mp.weixin.qq.com/s?__biz=MzA4NTEwNTI0Nw==&mid=2247484461&idx=1&sn=a5d4b5d523e277ca047b6bfb189eee92&chksm=9fdc4b1da8abc20bb11291d148e1f01dccb0d8c17d275613d5ef14d14acb8f979f54ff205a4c&scene=178&cur_album_id=1610763466921787393#rd)
[区属学校上岸攻略](https://mp.weixin.qq.com/s/6kf8-OsvvzVM1qPRB3irzg)
[市属学校上岸攻略](https://mp.weixin.qq.com/s/DKuWasdJ_5xPf6SREFFkxQ)
[教师俱乐部](https://mp.weixin.qq.com/s?__biz=MzA4NTEwNTI0Nw==&mid=2247484466&idx=1&sn=f6c8cd7413137c12eb4642bfcf79d9ec&chksm=9fdc4b02a8abc2145b1660dc522cae98e5d2491c3dcb46b2619785579ef8497590caacc6fe6a&scene=178&cur_album_id=1610763466921787393#rd)

包括我们教师社群也有很多优秀文章：
[如何从0开始上岸深圳教师](https://mp.weixin.qq.com/s/RM1DhUNSR7Ms6MPXtxhw0w)

这里有北京，上海浙江江苏等长三角，广州佛山中山珠海等珠三角，深圳公办和私立国际学校教师群体，欢迎大家一起交流学习。

**Comment by coder2gwy** [comment]
🚫广告，close了
