### ISSUE TITLE
关闭

### ISSUE THREAD

**Issue by Xbigfat** [coder2gwy/coder2gwy#66]
希望在这里能分享一下计算机专业的题目。我曾经参加过一次省考，考试专业有计算机。
但是计算机的题目 并非是非常深入的计算机知识，而是比较杂乱的，题目也很少有汇总和公开。

我考的那次，题目所涉及的方向五花八门：
1. excel 里的引用：绝对、相对引用
2. 计算某某文件的大小（码率xbitx时间啥的）
3. 给路由表和IP地址，计算路由器的下一跳（子网掩码）
4. 数据库SQL操作
5. 软件管理相关知识等

抛砖引玉，希望能得到一些真题，以便大家了解考试内容。
不过我参加的那次，给我的感觉就是很乱乱的知识都考，但都不是难题。

**Comment by xijinmu** [comment]
![image](https://user-images.githubusercontent.com/58028940/104908976-2c7f4d80-59c2-11eb-9931-18100b7eeb83.png)

**Comment by ManQ599** [comment]
深圳市考的题目才叫杂

之前在qzzn论坛提到大部分知识在<<计算机科学导论>>里有, 但是实际考试题目五花八门, 远比这本书提到的多

具体看考试大纲.

(一)基础知识

* 硬件基础知识
  1. 数制及其转换
  2. 算术运算和逻辑运算
  3. 计算机系统组成
  4. 计算机工作原理
  5. 计算机体系结构
* 操作系统
  1. 操作系统的基本概念
  2. 进程管理
  3. 作业管理
  4. 存储管理
  5. 文件管理
  6. 设备管理
  7. 常用操作系统
* C语言编程
  1. 程序的基本组成
  2. 选择结构
  3. 循环结构
  4. 模块设计
  5. 数组
  6. 指针
  7. 结构体
  8. 文件
* 算法和数据结构
  1. 基本概念
  2. 数组
  3. 链表
  4. 栈和队列
  5. 递归
  6. 树与森林
  7. 图
  8. 集合与搜索
  9. 索引与散列
  10. 排序
* 计算机网络与通信
  1. 计算机网络的基本概念
  2. 数据通信技术
  3. 网络体系结构
  4. 基本网络协议及标准
  5. 局域网技术
  6. 网络存储技术
  7. 视频会议技术
* 数据库
  1. 数据库基本概念
  2. 关系数据库
  3. 关系数据库设计理论
  4. 数据库设计
  5. 数据库语言(SQL)
  6. 数据库的保护
* 多媒体
  1. 音频、动画、图像、视频等技术原理
  2. 媒体的数字化过程及主流压缩标准。
* 信息安全
物理与环境安全、操作系统安全、网络通信安全、Web安全、数据安全、病毒防范、网络入侵检测、黑客攻击与防范、防火墙技术、信息化安全管理及实施、网络安全等级保护、信息安全风险评估、网络安全法基础。

(二)项目管理及系统规划

* 项目管理
软件工程基本概念、需求分析、系统设计、软件测试、系统测试，项目管理基础。
* 系统规划
信息系统规划，整体构架设计及系统整合。

(三)新技术发展趋势

* 云计算、物联网、人工智能、大数据、新一代移动网络、地理信息系统等技术的基础知识。

**Comment by hanwckf** [comment]
> 深圳市考的题目才叫杂
> 
> 之前在qzzn论坛提到大部分知识在<<计算机科学导论>>里有, 但是实际考试题目五花八门, 远比这本书提到的多
> 
> 具体看考试大纲.
> 
> (一)基础知识
> 
> * 硬件基础知识
>   
>   1. 数制及其转换
>   2. 算术运算和逻辑运算
>   3. 计算机系统组成
>   4. 计算机工作原理
>   5. 计算机体系结构
> * 操作系统
>   
>   1. 操作系统的基本概念
>   2. 进程管理
>   3. 作业管理
>   4. 存储管理
>   5. 文件管理
>   6. 设备管理
>   7. 常用操作系统
> * C语言编程
>   
>   1. 程序的基本组成
>   2. 选择结构
>   3. 循环结构
>   4. 模块设计
>   5. 数组
>   6. 指针
>   7. 结构体
>   8. 文件
> * 算法和数据结构
>   
>   1. 基本概念
>   2. 数组
>   3. 链表
>   4. 栈和队列
>   5. 递归
>   6. 树与森林
>   7. 图
>   8. 集合与搜索
>   9. 索引与散列
>   10. 排序
> * 计算机网络与通信
>   
>   1. 计算机网络的基本概念
>   2. 数据通信技术
>   3. 网络体系结构
>   4. 基本网络协议及标准
>   5. 局域网技术
>   6. 网络存储技术
>   7. 视频会议技术
> * 数据库
>   
>   1. 数据库基本概念
>   2. 关系数据库
>   3. 关系数据库设计理论
>   4. 数据库设计
>   5. 数据库语言(SQL)
>   6. 数据库的保护
> * 多媒体
>   
>   1. 音频、动画、图像、视频等技术原理
>   2. 媒体的数字化过程及主流压缩标准。
> * 信息安全
>   物理与环境安全、操作系统安全、网络通信安全、Web安全、数据安全、病毒防范、网络入侵检测、黑客攻击与防范、防火墙技术、信息化安全管理及实施、网络安全等级保护、信息安全风险评估、网络安全法基础。
> 
> (二)项目管理及系统规划
> 
> * 项目管理
>   软件工程基本概念、需求分析、系统设计、软件测试、系统测试，项目管理基础。
> * 系统规划
>   信息系统规划，整体构架设计及系统整合。
> 
> (三)新技术发展趋势
> 
> * 云计算、物联网、人工智能、大数据、新一代移动网络、地理信息系统等技术的基础知识。

深圳市考的实际难度远远超过那本导论

**Comment by Q3B0** [comment]
什么？省考还考专业知识？不都是行测和申论么

**Comment by ManQ599** [comment]
> 什么？省考还考专业知识？不都是行测和申论么

1. 执法勤务类(比如公安/司法/市场监督等行政管理类)要考行政法律专业知识, 公安岗一般要考公安专业知识
2. 去年安徽省考, 招录狱警计算机岗位的, 考计算机专业知识, 其他执法勤务岗位考了公安专业知识
3. 今年年初浙江省考, 公安岗位考了心理测评和公安专业知识
4. 深圳市考计算机岗位的要考计算机知识, 财会岗位考财会知识, 执法勤务考行政法律专业知识

**Comment by ManQ599** [comment]
> 难度

42.2分, 好多题目都瞎猜的, 比如信息安全和系统规划的题目.....

**Comment by Xbigfat** [comment]
> > 难度
> 
> 42.2分, 好多题目都瞎猜的, 比如信息安全和系统规划的题目.....

仁兄看的真准，我分享的就是2020年安徽省考，狱警岗位，成绩78

**Comment by ManQ599** [comment]
> > > 难度
> > 
> > 
> > 42.2分, 好多题目都瞎猜的, 比如信息安全和系统规划的题目.....
> 
> 仁兄看的真准，我分享的就是2020年安徽省考，狱警岗位，成绩78

阔以阔以, 我在隔壁徽京, 看了相关的岗位但最终没报名. 这岗位待遇好, 就是压力大些.

**Comment by hanwckf** [comment]
> > 难度
> 
> 42.2分, 好多题目都瞎猜的, 比如信息安全和系统规划的题目.....

我深圳这门计算机71.6，最终靠这个进面了。
当时考完感觉有80左右，结果回想一下题目里坑很多

**Comment by ManQ599** [comment]
> > > 难度
> > 
> > 
> > 42.2分, 好多题目都瞎猜的, 比如信息安全和系统规划的题目.....
> 
> 我深圳这门计算机71.6，最终靠这个进面了。
> 当时考完感觉有80左右，结果回想一下题目里坑很多

深圳哪个区的市场监督管理局？

**Comment by bebestmaple** [comment]
看着题目跟软考网络工程师、软考软件设计师好像。

**Comment by zzybb** [comment]
> > > 难度
> > 
> > 
> > 42.2分, 好多题目都瞎猜的, 比如信息安全和系统规划的题目.....
> 
> 我深圳这门计算机71.6，最终靠这个进面了。
> 当时考完感觉有80左右，结果回想一下题目里坑很多

大佬方便指导吗 可以付费 我也要考深圳市考 是应届生
