### ISSUE TITLE
【顶】为什么本科考公是当代大学生的唯一出路?

### ISSUE THREAD

**Issue by tczpl** [coder2gwy/coder2gwy#7]
# 一、你将拥有一个轻松的青春
如果选择了本科考公，从高考完开始，无论是一本二本，都可以开始混了。
直到考前两到三个月开始复习，考上后接着混，考不上就明年继续，一年那么多机会总能考上。
反观其他出路，绩点、社团、比赛、实习，足以让你的青春充满焦虑。
# 二、你将拥有一个轻松的中年
公务员多数可以五六点迎着晚霞回家打游戏，不会错过孩子的童年和长辈的晚年。
一二线城市公务员的薪资，足以媲美互联网大厂。
三四线城市公务员的地位，足以让你在家庭聚会时不逊于百万老总。
反观其他出路，绩效、加班、努力的后浪，足以让你的中年充满焦虑。
# 三、你将拥有一个轻松的通道
与企业相比，公务员的上升通道一直为人诟病。但去哪里卷不是卷呢？
你愿意加班愿意卷，在企业里才升的上去。城市和单位选对了，在公务员里同样升的上去。
选择公务员，不意味着没有上升通道，只是在通道中走累了，有选择可以歇一歇。
反观其他出路，聪明人那么多，你确定你能拼到财富自由而不是拼多多吗？自由了，人也老了。
# 四、错过了怎么办
请勿焦虑，可以上[炒币信息网](http://www.ChaoBi.info)学习购买比特币等。

<非原创，转载自[考公网 KaoGongWang.com](http://KaoGongWang.com)>

**Comment by weimumu** [comment]
本科转正定一级科员，硕士转正定副科待遇，副科相当于一个区局副局长或者一个副镇长，博士不知道是定正科还是副处待遇了，应该是正科吧，相当于我们局局长待遇或者一个镇长镇书记的待遇

**Comment by weimumu** [comment]
博士考公才是最好的

**Comment by weimumu** [comment]
博士考公才是最好的，本科转正定一级科员，硕士转正定副科待遇，副科相当于一个区局副局长或者一个副镇长，博士定正科或者副处待遇了，应该是正科吧，相当于局长待遇或者一个镇长镇书记的待遇

**Comment by cnyyl** [comment]
对啊，我的同学最近都在疯狂学Java，想着三月份就去实习，把我也搞得很焦虑。我的职业规划又不想去互联网，也不想找实习，但是不和他们一起去实习怕到时候找不到工作，愁啊。

**Comment by cnyyl** [comment]
有人的地方就有江湖，关系户、勾心斗角、派系不是体制内的专属。公务员至少你不违纪违法能干到退休，体制外因为有竞争有末位淘汰，为了赚钱，各种骚操作反而会更夸张。

**Comment by L379** [comment]
看到最后我笑了，也哭了，哎，到处都是镰刀等着我们这些韭菜们头伸过去

**Comment by danielzhou82** [comment]
论文发了吗

**Comment by lightning-li** [comment]
但是院士是享受国务院津贴的啊，你不考虑考虑往这个方向努力努力

**Comment by chenxu2048** [comment]
院士是享受国家特殊津贴的

**Comment by longqh3** [comment]
租鸡青一，天下大同:)

**Comment by Demonhero0** [comment]
第四步点击快进，快进到退休

**Comment by Demonhero0** [comment]
第四步点击快进

**Comment by coder2gwy** [comment]
🚫广告，已close。
